/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminPanelIndexRouteImport } from './routes/admin-panel.index'
import { Route as AdminPanelApprovalsRouteImport } from './routes/admin-panel.approvals'
import { Route as AdminPanelCompaniesRouteImport } from './routes/admin-panel.companies'
import { Route as AdminPanelDashboardRouteImport } from './routes/admin-panel.dashboard'
import { Route as AdminPanelInterviewsRouteImport } from './routes/admin-panel.interviews'
import { Route as AdminPanelLoginRouteImport } from './routes/admin-panel.login'
import { Route as AdminPanelOffersRouteImport } from './routes/admin-panel.offers'
import { Route as AdminPanelSettingsRouteImport } from './routes/admin-panel.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPanelSettingsIndexRouteImport } from './routes/admin-panel.settings.index'
import { Route as AdminPanelSettingsAutomationRouteImport } from './routes/admin-panel.settings.automation'
import { Route as AdminPanelSettingsGuidelinesRouteImport } from './routes/admin-panel.settings.guidelines'
import { Route as AdminPanelSettingsTeamRouteImport } from './routes/admin-panel.settings.team'
import { Route as AdminPanelSettingsTemplatesRouteImport } from './routes/admin-panel.settings.templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelIndexRoute = AdminPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelApprovalsRoute = AdminPanelApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelCompaniesRoute = AdminPanelCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDashboardRoute = AdminPanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelInterviewsRoute = AdminPanelInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelLoginRoute = AdminPanelLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelOffersRoute = AdminPanelOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelSettingsRoute = AdminPanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelSettingsIndexRoute = AdminPanelSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPanelSettingsRoute,
} as any)
const AdminPanelSettingsAutomationRoute =
  AdminPanelSettingsAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AdminPanelSettingsRoute,
  } as any)
const AdminPanelSettingsGuidelinesRoute =
  AdminPanelSettingsGuidelinesRouteImport.update({
    id: '/guidelines',
    path: '/guidelines',
    getParentRoute: () => AdminPanelSettingsRoute,
  } as any)
const AdminPanelSettingsTeamRoute = AdminPanelSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminPanelSettingsRoute,
} as any)
const AdminPanelSettingsTemplatesRoute =
  AdminPanelSettingsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AdminPanelSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin-panel/approvals': typeof AdminPanelApprovalsRoute
  '/admin-panel/companies': typeof AdminPanelCompaniesRoute
  '/admin-panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin-panel/interviews': typeof AdminPanelInterviewsRoute
  '/admin-panel/login': typeof AdminPanelLoginRoute
  '/admin-panel/offers': typeof AdminPanelOffersRoute
  '/admin-panel/settings': typeof AdminPanelSettingsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin-panel/': typeof AdminPanelIndexRoute
  '/admin-panel/settings/automation': typeof AdminPanelSettingsAutomationRoute
  '/admin-panel/settings/guidelines': typeof AdminPanelSettingsGuidelinesRoute
  '/admin-panel/settings/team': typeof AdminPanelSettingsTeamRoute
  '/admin-panel/settings/templates': typeof AdminPanelSettingsTemplatesRoute
  '/admin-panel/settings/': typeof AdminPanelSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin-panel/approvals': typeof AdminPanelApprovalsRoute
  '/admin-panel/companies': typeof AdminPanelCompaniesRoute
  '/admin-panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin-panel/interviews': typeof AdminPanelInterviewsRoute
  '/admin-panel/login': typeof AdminPanelLoginRoute
  '/admin-panel/offers': typeof AdminPanelOffersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin-panel': typeof AdminPanelIndexRoute
  '/admin-panel/settings/automation': typeof AdminPanelSettingsAutomationRoute
  '/admin-panel/settings/guidelines': typeof AdminPanelSettingsGuidelinesRoute
  '/admin-panel/settings/team': typeof AdminPanelSettingsTeamRoute
  '/admin-panel/settings/templates': typeof AdminPanelSettingsTemplatesRoute
  '/admin-panel/settings': typeof AdminPanelSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin-panel/approvals': typeof AdminPanelApprovalsRoute
  '/admin-panel/companies': typeof AdminPanelCompaniesRoute
  '/admin-panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin-panel/interviews': typeof AdminPanelInterviewsRoute
  '/admin-panel/login': typeof AdminPanelLoginRoute
  '/admin-panel/offers': typeof AdminPanelOffersRoute
  '/admin-panel/settings': typeof AdminPanelSettingsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin-panel/': typeof AdminPanelIndexRoute
  '/admin-panel/settings/automation': typeof AdminPanelSettingsAutomationRoute
  '/admin-panel/settings/guidelines': typeof AdminPanelSettingsGuidelinesRoute
  '/admin-panel/settings/team': typeof AdminPanelSettingsTeamRoute
  '/admin-panel/settings/templates': typeof AdminPanelSettingsTemplatesRoute
  '/admin-panel/settings/': typeof AdminPanelSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-panel'
    | '/dashboard'
    | '/admin-panel/approvals'
    | '/admin-panel/companies'
    | '/admin-panel/dashboard'
    | '/admin-panel/interviews'
    | '/admin-panel/login'
    | '/admin-panel/offers'
    | '/admin-panel/settings'
    | '/admin/login'
    | '/admin-panel/'
    | '/admin-panel/settings/automation'
    | '/admin-panel/settings/guidelines'
    | '/admin-panel/settings/team'
    | '/admin-panel/settings/templates'
    | '/admin-panel/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin-panel/approvals'
    | '/admin-panel/companies'
    | '/admin-panel/dashboard'
    | '/admin-panel/interviews'
    | '/admin-panel/login'
    | '/admin-panel/offers'
    | '/admin/login'
    | '/admin-panel'
    | '/admin-panel/settings/automation'
    | '/admin-panel/settings/guidelines'
    | '/admin-panel/settings/team'
    | '/admin-panel/settings/templates'
    | '/admin-panel/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-panel'
    | '/dashboard'
    | '/admin-panel/approvals'
    | '/admin-panel/companies'
    | '/admin-panel/dashboard'
    | '/admin-panel/interviews'
    | '/admin-panel/login'
    | '/admin-panel/offers'
    | '/admin-panel/settings'
    | '/admin/login'
    | '/admin-panel/'
    | '/admin-panel/settings/automation'
    | '/admin-panel/settings/guidelines'
    | '/admin-panel/settings/team'
    | '/admin-panel/settings/templates'
    | '/admin-panel/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel/': {
      id: '/admin-panel/'
      path: '/'
      fullPath: '/admin-panel/'
      preLoaderRoute: typeof AdminPanelIndexRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/approvals': {
      id: '/admin-panel/approvals'
      path: '/approvals'
      fullPath: '/admin-panel/approvals'
      preLoaderRoute: typeof AdminPanelApprovalsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/companies': {
      id: '/admin-panel/companies'
      path: '/companies'
      fullPath: '/admin-panel/companies'
      preLoaderRoute: typeof AdminPanelCompaniesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/dashboard': {
      id: '/admin-panel/dashboard'
      path: '/dashboard'
      fullPath: '/admin-panel/dashboard'
      preLoaderRoute: typeof AdminPanelDashboardRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/interviews': {
      id: '/admin-panel/interviews'
      path: '/interviews'
      fullPath: '/admin-panel/interviews'
      preLoaderRoute: typeof AdminPanelInterviewsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/login': {
      id: '/admin-panel/login'
      path: '/login'
      fullPath: '/admin-panel/login'
      preLoaderRoute: typeof AdminPanelLoginRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/offers': {
      id: '/admin-panel/offers'
      path: '/offers'
      fullPath: '/admin-panel/offers'
      preLoaderRoute: typeof AdminPanelOffersRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/settings': {
      id: '/admin-panel/settings'
      path: '/settings'
      fullPath: '/admin-panel/settings'
      preLoaderRoute: typeof AdminPanelSettingsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin-panel/settings/': {
      id: '/admin-panel/settings/'
      path: '/'
      fullPath: '/admin-panel/settings/'
      preLoaderRoute: typeof AdminPanelSettingsIndexRouteImport
      parentRoute: typeof AdminPanelSettingsRoute
    }
    '/admin-panel/settings/automation': {
      id: '/admin-panel/settings/automation'
      path: '/automation'
      fullPath: '/admin-panel/settings/automation'
      preLoaderRoute: typeof AdminPanelSettingsAutomationRouteImport
      parentRoute: typeof AdminPanelSettingsRoute
    }
    '/admin-panel/settings/guidelines': {
      id: '/admin-panel/settings/guidelines'
      path: '/guidelines'
      fullPath: '/admin-panel/settings/guidelines'
      preLoaderRoute: typeof AdminPanelSettingsGuidelinesRouteImport
      parentRoute: typeof AdminPanelSettingsRoute
    }
    '/admin-panel/settings/team': {
      id: '/admin-panel/settings/team'
      path: '/team'
      fullPath: '/admin-panel/settings/team'
      preLoaderRoute: typeof AdminPanelSettingsTeamRouteImport
      parentRoute: typeof AdminPanelSettingsRoute
    }
    '/admin-panel/settings/templates': {
      id: '/admin-panel/settings/templates'
      path: '/templates'
      fullPath: '/admin-panel/settings/templates'
      preLoaderRoute: typeof AdminPanelSettingsTemplatesRouteImport
      parentRoute: typeof AdminPanelSettingsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdminPanelSettingsRouteChildren {
  AdminPanelSettingsAutomationRoute: typeof AdminPanelSettingsAutomationRoute
  AdminPanelSettingsGuidelinesRoute: typeof AdminPanelSettingsGuidelinesRoute
  AdminPanelSettingsTeamRoute: typeof AdminPanelSettingsTeamRoute
  AdminPanelSettingsTemplatesRoute: typeof AdminPanelSettingsTemplatesRoute
  AdminPanelSettingsIndexRoute: typeof AdminPanelSettingsIndexRoute
}

const AdminPanelSettingsRouteChildren: AdminPanelSettingsRouteChildren = {
  AdminPanelSettingsAutomationRoute: AdminPanelSettingsAutomationRoute,
  AdminPanelSettingsGuidelinesRoute: AdminPanelSettingsGuidelinesRoute,
  AdminPanelSettingsTeamRoute: AdminPanelSettingsTeamRoute,
  AdminPanelSettingsTemplatesRoute: AdminPanelSettingsTemplatesRoute,
  AdminPanelSettingsIndexRoute: AdminPanelSettingsIndexRoute,
}

const AdminPanelSettingsRouteWithChildren =
  AdminPanelSettingsRoute._addFileChildren(AdminPanelSettingsRouteChildren)

interface AdminPanelRouteChildren {
  AdminPanelApprovalsRoute: typeof AdminPanelApprovalsRoute
  AdminPanelCompaniesRoute: typeof AdminPanelCompaniesRoute
  AdminPanelDashboardRoute: typeof AdminPanelDashboardRoute
  AdminPanelInterviewsRoute: typeof AdminPanelInterviewsRoute
  AdminPanelLoginRoute: typeof AdminPanelLoginRoute
  AdminPanelOffersRoute: typeof AdminPanelOffersRoute
  AdminPanelSettingsRoute: typeof AdminPanelSettingsRouteWithChildren
  AdminPanelIndexRoute: typeof AdminPanelIndexRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelApprovalsRoute: AdminPanelApprovalsRoute,
  AdminPanelCompaniesRoute: AdminPanelCompaniesRoute,
  AdminPanelDashboardRoute: AdminPanelDashboardRoute,
  AdminPanelInterviewsRoute: AdminPanelInterviewsRoute,
  AdminPanelLoginRoute: AdminPanelLoginRoute,
  AdminPanelOffersRoute: AdminPanelOffersRoute,
  AdminPanelSettingsRoute: AdminPanelSettingsRouteWithChildren,
  AdminPanelIndexRoute: AdminPanelIndexRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
