import type { CountryDetails } from "../types";

export const COUNTRY_OPTIONS: Record<string, CountryDetails> = {
  "United States": {
    name: "United States",
    code: "US",
    phonePrefix: "+1",
    timezone: "EST / PST (UTC-5/UTC-8)",
    currency: "USD ($)",
    compliance: "FLSA, EEOC, SOC2, OSHA",
    payroll: "W-2 & 1099 Standard",
  },
  "United Kingdom": {
    name: "United Kingdom",
    code: "GB",
    phonePrefix: "+44",
    timezone: "GMT / BST (UTC+0)",
    currency: "GBP (£)",
    compliance: "UK GDPR, Employment Rights Act",
    payroll: "PAYE & National Insurance",
  },
  India: {
    name: "India",
    code: "IN",
    phonePrefix: "+91",
    timezone: "IST (UTC+5:30)",
    currency: "INR (₹)",
    compliance: "EPF, ESI, Gratuity Act, POSH",
    payroll: "Indian Statutory Payroll & Form 16",
  },
  Canada: {
    name: "Canada",
    code: "CA",
    phonePrefix: "+1",
    timezone: "EST / PST (UTC-5)",
    currency: "CAD ($)",
    compliance: "PIPEDA, Provincial Labour Codes",
    payroll: "CPP & EI Statutory Payroll",
  },
  Germany: {
    name: "Germany",
    code: "DE",
    phonePrefix: "+49",
    timezone: "CET / CEST (UTC+1)",
    currency: "EUR (€)",
    compliance: "EU GDPR, Works Council (Betriebsrat)",
    payroll: "German Social Security & Tax ID",
  },
  France: {
    name: "France",
    code: "FR",
    phonePrefix: "+33",
    timezone: "CET / CEST (UTC+1)",
    currency: "EUR (€)",
    compliance: "EU GDPR, Code du Travail",
    payroll: "URSSAF Statutory Payroll",
  },
  Australia: {
    name: "Australia",
    code: "AU",
    phonePrefix: "+61",
    timezone: "AEST / AEDT (UTC+10)",
    currency: "AUD ($)",
    compliance: "Fair Work Act, NES Rules",
    payroll: "STP Phase 2 & Superannuation",
  },
  Singapore: {
    name: "Singapore",
    code: "SG",
    phonePrefix: "+65",
    timezone: "SGT (UTC+8)",
    currency: "SGD ($)",
    compliance: "MOM Employment Act",
    payroll: "CPF (Central Provident Fund)",
  },
  Japan: {
    name: "Japan",
    code: "JP",
    phonePrefix: "+81",
    timezone: "JST (UTC+9)",
    currency: "JPY (¥)",
    compliance: "Labor Standards Act, MyNumber",
    payroll: "Japanese Shakai Hoken",
  },
  "United Arab Emirates": {
    name: "United Arab Emirates",
    code: "AE",
    phonePrefix: "+971",
    timezone: "GST (UTC+4)",
    currency: "AED (د.إ)",
    compliance: "UAE Labour Law, MOHRE",
    payroll: "WPS (Wage Protection System)",
  },
  Brazil: {
    name: "Brazil",
    code: "BR",
    phonePrefix: "+55",
    timezone: "BRT (UTC-3)",
    currency: "BRL (R$)",
    compliance: "CLT Labour Laws, LGPD",
    payroll: "eSocial, FGTS & INSS",
  },
  Other: {
    name: "Other Country",
    code: "OTHER",
    phonePrefix: "+1",
    timezone: "UTC Standard",
    currency: "USD ($)",
    compliance: "Global Compliance Standard",
    payroll: "Multi-Currency Global Payroll",
  },
};

export const COMPANY_SIZE_OPTIONS = [
  "1–10",
  "11–25",
  "26–50",
  "51–100",
  "101–250",
  "251–500",
  "501–1000",
  "1000+",
] as const;

export const INDUSTRY_OPTIONS = [
  "IT Services",
  "Product Company",
  "Consulting",
  "Manufacturing",
  "Healthcare",
  "Banking",
  "Education",
  "E-commerce",
  "Logistics",
  "Construction",
  "Media",
  "Others",
] as const;

export const REFERRAL_SOURCE_OPTIONS = [
  "Google",
  "LinkedIn",
  "Employee",
  "Friend",
  "Advertisement",
  "Sales Team",
  "Other",
] as const;
