/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAutomationRouteImport } from './routes/settings.automation'
import { Route as SettingsGuidelinesRouteImport } from './routes/settings.guidelines'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsTemplatesRouteImport } from './routes/settings.templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutomationRoute = SettingsAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGuidelinesRoute = SettingsGuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/guidelines': typeof SettingsGuidelinesRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/guidelines': typeof SettingsGuidelinesRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/guidelines': typeof SettingsGuidelinesRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/automation'
    | '/settings/guidelines'
    | '/settings/team'
    | '/settings/templates'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/automation'
    | '/settings/guidelines'
    | '/settings/team'
    | '/settings/templates'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/automation'
    | '/settings/guidelines'
    | '/settings/team'
    | '/settings/templates'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/automation': {
      id: '/settings/automation'
      path: '/automation'
      fullPath: '/settings/automation'
      preLoaderRoute: typeof SettingsAutomationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/guidelines': {
      id: '/settings/guidelines'
      path: '/guidelines'
      fullPath: '/settings/guidelines'
      preLoaderRoute: typeof SettingsGuidelinesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/templates': {
      id: '/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAutomationRoute: typeof SettingsAutomationRoute
  SettingsGuidelinesRoute: typeof SettingsGuidelinesRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAutomationRoute: SettingsAutomationRoute,
  SettingsGuidelinesRoute: SettingsGuidelinesRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
